kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./metadata/redhat-catalogs
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
    targetCatalog: my-redhat-v413-catalog
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.8
        minVersion: '2.8.2'
        maxVersion: '2.8.2'
